export * from './home.model';
export * from './slide.model';
export * from './project.model';
export * from './projectType.model';
export * from './about.model';
export * from './contact.model';
export * from './image.model';
export * from './postCategory.model';
export * from './post.model';
